Add scheduling
alphagov/travel-advice-publisher pull request #1831
Opened 2024-03-08 10:16 UTC by lauraghiorghisor-tw

⚠️ This repo is Continuously Deployed: make sure you [follow the guidance](https://docs.publishing.service.gov.uk/manual/development-pipeline.html#merge-your-own-pull-request) ⚠️

2024-03-15 10:23 UTC, lauraghiorghisor-tw commented on app/controllers/admin/editions_controller.rb
> +    if @edition.update(permitted_edition_attributes) && @edition.has_valid_change_description_for_scheduling?
This `has_valid_change_description_for_scheduling?` -> we have validation on the state in the model anyway, which would produce an error on the scheduling form submit, but to keep the same pattern we have for "Save & Publish", we thought it would be nice to error before we redirect to `/schedulings/new`

2024-03-15 10:35 UTC, lauraghiorghisor-tw commented on app/workers/publish_scheduled_edition_worker.rb
> +    raise WorkerError.new(self, e, "Edition must be in a scheduled state")
Now, this error is misleading.

2024-03-15 10:44 UTC, lauraghiorghisor-tw commented on spec/models/travel_advice_edition_spec.rb
> +    context "#schedule_for_publication" do
Used to have these in the controller tests. Moved them here, kept the controller tests slimmer.Used to have these in the controller tests. Moved them here, kept the controller tests slimmer.

2024-03-15 10:46 UTC, lauraghiorghisor-tw commented on app/models/travel_advice_edition.rb
> +    notifier.patch_links(self)
Not sure if we require the patch links too.

2024-03-15 10:59 UTC, lauraghiorghisor-tw commented on spec/requests/request_tracing_spec.rb
> +    Sidekiq::Worker.clear_all
Hoping this fixes it. 
Think the drain_all in the test was getting the worker to run and it couldn't find the edition anymore.
![Screenshot 2024-03-15 at 10 47 54](https://github.com/alphagov/travel-advice-publisher/assets/91544378/98b850ea-b372-4293-9c5c-5a59f3b14ca1)

2024-03-15 11:16 UTC, lauraghiorghisor-tw commented on app/workers/publish_scheduled_edition_worker.rb
> +      notifier.put_content(edition)
We are now doing a `put_content` when we save the draft at the point of scheduling (see `schedule_for_publication` on the `TravelAdviceEdition` model) -> we don't need it here anymore, but also doesn't hurt to have it?

2024-03-15 12:52 UTC, ryanb-gds requested changes
There's a lot here, I think it would be great to get on a call this afternoon and to talk through it all. Looking good though

2024-03-15 12:52 UTC, ryanb-gds commented on app/workers/publish_scheduled_edition_worker.rb
> +      notifier.put_content(edition)
I don't think we should be doing this in either place, should we? In my head put content should happen only when the edition content is saved? It might be that the existing code isn't really working how I feel it should though.

In any case, I don't think "not hurting" is sufficient justification for making an API call 😉

2024-03-15 12:52 UTC, ryanb-gds commented on app/workers/publish_scheduled_edition_worker.rb
> +    raise WorkerError.new(self, e, "Edition must be in a scheduled state")
If it could, then maybe it should 👀

2024-03-15 12:52 UTC, ryanb-gds commented on spec/factories.rb
> +    scheduled_publication_time { 1.hour.from_now }
Shouldn't we do this in the `after` callback as well? It doesn't make sense for the time to be set but the state not to be scheduled, right?

2024-03-15 12:52 UTC, ryanb-gds commented on spec/models/travel_advice_edition_spec.rb
> +      published.reload
This... doesn't feel that it should be necessary. Wonder what bit of shared state is causing that problem 🤔

2024-03-15 14:25 UTC, lauraghiorghisor-tw commented on app/controllers/application_controller.rb
> +    current_user.has_permission?(User::SCHEDULE_EDITION_PERMISSION)
It is done https://trello.com/c/1TKIO84l/2374-travel-advice-publisher-improvements-remove-feature-flag-and-release

2024-03-15 14:28 UTC, lauraghiorghisor-tw commented on app/models/travel_advice_edition.rb
> +    errors.add(:change_description, "can't be blank on schedule")
We have a similar `We had some problems publishing: Change description can't be blank on publish.`

2024-03-15 14:32 UTC, lauraghiorghisor-tw commented on spec/controllers/admin/schedulings_controller_spec.rb
> +      expect(flash[:notice]).to eq "#{@country.name} travel advice is scheduled to publish on #{3.hours.from_now.strftime('%B %d, %Y %H:%M %Z')}."
We had those assertions on the queue size here, moved them in the model tests. Perhaps a single assertion on the queue size can live here and then the model tests can cover the args in more detail?

2024-03-15 14:39 UTC, lauraghiorghisor-tw commented on app/models/travel_advice_edition.rb
> +    notifier.patch_links(self)
So there are no on save callbacks or anything here, the put content calls on save draft are actioned from the edition controller when saving a simple draft. 

Our scheduled state is still a draft, and when we save nothing gets sent to publishing-api. If we want the preview links to point to an updated draft content store version, then we need to do a put content.

2024-03-15 14:40 UTC, lauraghiorghisor-tw commented on app/workers/publish_scheduled_edition_worker.rb
> +      notifier.put_content(edition)
I cannot quite think whether or not any potential changes of edition would need to be sent once you make the first put_content call on schedule. I would assume NOT, since the edition is not editable whilst scheduled?

2024-03-15 14:41 UTC, lauraghiorghisor-tw commented on app/assets/stylesheets/date_time.scss
> +}
I did not try it without them. WH overrides them 😶‍🌫️

2024-03-18 10:41 UTC, ryanb-gds approved these changes
Great work @lauraghiorghisor-tw and @baisa - exciting to see this ready to merge! 🚀

2024-03-18 10:41 UTC, ryanb-gds commented on app/models/travel_advice_edition.rb
> +  end
I think you could have applied this validation rule in the state machine config for the draft state (like for the can't edit in published state validation) if you wanted. Then you could avoid the `== draft` check here. Minor point though, not required to merge

2024-03-18 14:16 UTC, ryanb-gds approved these changes
🤖

2024-03-19 09:14 UTC, merged