Upgrade ruby 2.7
alphagov/travel-advice-publisher pull request #962
Opened 2020-09-17 11:20 UTC by benbaumann95

This PR contains the changes necessary for the app to run on Ruby 2.7.1.

The version of Ruby is left the same, since there is a script that can be run after all the apps have been updated to update the version all at once

- Tested locally with ruby 2.7.1 and 2.6.6
- Upon upgrading to 2.7.1, there was a whirlwind of deprecation warnings and incompatibility issues with formtastic / formatstic-bootstrap gem as explained in d72b3a1
- Re-wrote all formtastic forms natively. No cosmetic change but should be far more future-proof and easier to maintain

2020-09-25 10:00 UTC, cdccollins commented on app/views/admin/editions/_change_notes.html.erb
> +        <div class="form-group radio_buttons input required" id="edition_update_type_input">
I don't see the "required" in the formtastic version, though I guess it probably doesn't make too much difference?

2020-09-25 10:01 UTC, cdccollins commented on app/views/admin/editions/_change_notes.html.erb
> +                <%= f.radio_button :update_type, :minor, class: "js-edition-update-minor", disabled: !@edition.draft?  %>
I think this is a set of radio buttons - the collection in the formtastic shows what the options should be. 
i.e.
[] A type, style...
[] Minor

2020-09-25 10:16 UTC, cdccollins requested changes

2020-09-25 10:16 UTC, cdccollins commented on app/views/admin/editions/_change_notes.html.erb
> +              <%= f.radio_button :update_type, :major, class: "js-edition-update-major", disabled: !@edition.draft?  %>
Same as above

2020-09-25 10:16 UTC, cdccollins commented on app/views/admin/editions/_change_notes.html.erb
> +        <%= f.label :change_description, class: "control-label" do %>
Could you not do the simpler one-liner version here?

2020-09-25 10:16 UTC, cdccollins commented on app/views/admin/editions/_part.html.erb
> -                      :hint => true,
This adds a hint to the form - I don't see it in your version

2020-09-25 10:16 UTC, cdccollins commented on app/views/admin/editions/_part.html.erb
> -          <%= f.input :order, :as => :hidden, :input_html => { :class => 'order', :disabled => !editable } %>
I've been interpreting this as f.hidden_fields, rather than a whole bit of the form that's just hidden?

2020-09-25 10:16 UTC, cdccollins commented on app/views/admin/editions/edit.html.erb
> +                <%= f.text_area :summary, disabled: !@edition.draft?, class: "input-md-8 form-control", rows: 20 %>
Where did the `rows: 20` come from?

2020-09-25 10:16 UTC, cdccollins commented on app/views/admin/editions/edit.html.erb
> -            <%= f.add_associated_jquery_template :parts, :partial => '/admin/editions/part',
Could the file `admin/editions/parts` be deleted now it's not used here?

2020-09-28 09:38 UTC, benbaumann95 commented on app/views/admin/editions/_change_notes.html.erb
> +                <%= f.radio_button :update_type, :minor, class: "js-edition-update-minor", disabled: !@edition.draft?  %>
Ah good spot!

2020-09-28 09:39 UTC, benbaumann95 commented on app/views/admin/editions/_change_notes.html.erb
> +        <%= f.label :change_description, class: "control-label" do %>
It's for the required * formatting to be inline

2020-09-28 09:41 UTC, benbaumann95 commented on app/views/admin/editions/edit.html.erb
> +                <%= f.text_area :summary, disabled: !@edition.draft?, class: "input-md-8 form-control", rows: 20 %>
Was auto-generated by formtastic 👍

2020-09-28 09:47 UTC, benbaumann95 commented on app/views/admin/editions/_change_notes.html.erb
> +                <%= f.radio_button :update_type, :minor, class: "js-edition-update-minor", disabled: !@edition.draft?  %>
Hmm actually i just checked against master. It is like that:
![Screenshot 2020-09-28 at 10 46 59](https://user-images.githubusercontent.com/34001723/94417423-f6e6f800-0177-11eb-8390-c72f5c6c9449.png)

2020-09-28 09:50 UTC, benbaumann95 commented on app/views/admin/editions/_change_notes.html.erb
> +        <div class="form-group radio_buttons input required" id="edition_update_type_input">
Just checked, the html produces it on master so that's why I added the classname in. But i'm not even sure it does anything so can remove it

2020-09-28 09:53 UTC, benbaumann95 commented on app/views/admin/editions/_change_notes.html.erb
> +                <%= f.radio_button :update_type, :minor, class: "js-edition-update-minor", disabled: !@edition.draft?  %>
The html generated on the left and here is the same so i'm thinking to leave as is. 
Have you done a comparison with master to see if i'm not talking waffle ? 😃

2020-09-28 09:58 UTC, benbaumann95 commented on app/views/admin/editions/_part.html.erb
> -                      :hint => true,
Hmm I can't see how this hint is added to the html. It doesn't show anything when I'm on this section? Could you look if you get the chance

2020-09-28 10:01 UTC, benbaumann95 commented on app/views/admin/editions/edit.html.erb
> -            <%= f.add_associated_jquery_template :parts, :partial => '/admin/editions/part',
It's used here https://github.com/alphagov/travel-advice-publisher/pull/962/files#diff-6dcd46248805ebbd5e90bfaab2eaae77R136

2020-09-28 11:33 UTC, cdccollins commented on app/views/admin/editions/_change_notes.html.erb
> +                <%= f.radio_button :update_type, :minor, class: "js-edition-update-minor", disabled: !@edition.draft?  %>
Ah ok just checked on master, yep you're right.

2020-09-28 11:33 UTC, cdccollins commented on app/views/admin/editions/_change_notes.html.erb
> +        <%= f.label :change_description, class: "control-label" do %>
On master the public change note doesn't have the little asterisk by it

2020-09-28 11:36 UTC, cdccollins commented on app/views/admin/editions/_part.html.erb
> -                      :hint => true,
Kinda strange, there doesn't seem to be a hint on master but they want the hint to be true?

2020-09-28 11:38 UTC, cdccollins commented on app/views/admin/editions/edit.html.erb
> +                <%= f.file_field :document, type: "file", class: "form-control" %>
The form control class here is adding a weird box around it:

<img width="836" alt="Screenshot 2020-09-28 at 11 32 22" src="https://user-images.githubusercontent.com/35098639/94427663-5bf61a00-0187-11eb-9af6-fe5cfc5f0552.png">

Master is: 

<img width="807" alt="Screenshot 2020-09-28 at 12 37 44" src="https://user-images.githubusercontent.com/35098639/94427727-70d2ad80-0187-11eb-9b42-9e62a4ccbd83.png">

2020-09-28 11:52 UTC, benbaumann95 commented on app/views/admin/editions/edit.html.erb
> +                <%= f.file_field :document, type: "file", class: "form-control" %>
Aha thanks for spotting that

2020-09-28 14:08 UTC, benbaumann95 commented on app/views/admin/editions/_part.html.erb
> -                      :hint => true,
Yeah it's weird. Will just stick with the matching html

2020-09-28 14:08 UTC, benbaumann95 commented on app/views/admin/editions/_part.html.erb
> -          <%= f.input :order, :as => :hidden, :input_html => { :class => 'order', :disabled => !editable } %>
good point 👍

2020-09-28 14:13 UTC, cdccollins commented on app/views/admin/editions/_part.html.erb
> +            <%= f.label :title, class: "control-label" do %>
just noticed that this is a label for title when it should be for body?

2020-09-28 14:14 UTC, cdccollins commented on app/views/admin/editions/_part.html.erb
> +        <%= f.hidden_field :order, disabled: !editable, class: "order form-control" %>
You don't need the class "form-control" if it's hidden... but that's a tiny point

2020-09-28 15:04 UTC, benbaumann95 commented on app/views/admin/editions/_part.html.erb
> +            <%= f.text_field :body, required: true, disabled: !editable, class: "slug input-md-8 form-control" %>
This must have been a late night PR 😭

2020-09-28 15:12 UTC, cdccollins approved these changes
🎉 🎉

2020-09-29 13:45 UTC, merged